In [1]:
# Import Modules
import pandas as pd
import matplotlib.pyplot as plt
import plotly 
from sklearn.linear_model import LinearRegression
import statsmodels.api as sm 
import numpy as np

In [5]:
# Load data
data = pd.read_excel("/Users/talhajamal/Desktop/Code/Regression_Analysis/data/data_coursework_Q2.xls")
data["Yt_US"] = (data['USR'] > 0).astype(int)
data["Yt_EUR"] = (data['ESR'] > 0).astype(int)
data.head()

,mth,ESR,USR,EIF,ERECB,EFX,EDY,ESP,UIF,URR,UDY,UOIL,Yt_US,Yt_EUR
0,31-gen-85,0.0559,0.0690,0.0209,1.6094,0.0025,1.1663,2.206,0.0396,2.1668,1.4951,0.0210,1,1
1,1985-02-28 00:00:00,0.0331,0.0066,0.0235,1.6582,0.0556,1.1474,2.374,0.0347,2.1679,1.4929,0.0094,1,1
2,1985-03-31 00:00:00,-0.0027,-0.0089,0.0249,1.6582,-0.0813,1.1474,2.142,0.0354,2.1494,1.5041,0.0582,0,0
3,1985-04-30 00:00:00,0.0226,-0.0057,0.0250,1.6582,0.0049,1.1569,2.023,0.0372,2.1494,1.5173,-0.0269,0,1
4,31-mag-85,0.0424,0.0504,0.0236,1.6582,-0.0127,1.1282,1.856,0.0352,2.0334,1.4679,0.0108,1,1